=== jonathanhickford/rpi-shairport-sync/shairport-sync/man/xmltoman.dtd
<!--
  This is part of shairport-sync.
  Copyright (c) Mike Brady 2014
  All rights reserved.
 
  Permission is hereby granted, free of charge, to any person
  obtaining a copy of this software and associated documentation
  files (the "Software"), to deal in the Software without
  restriction, including without limitation the rights to use,
  copy, modify, merge, publish, distribute, sublicense, and/or
  sell copies of the Software, and to permit persons to whom the
  Software is furnished to do so, subject to the following conditions:
 
  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Software.
 
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
  OTHER DEALINGS IN THE SOFTWARE.
-->

<!ELEMENT manpage (synopsis | description | section | options | seealso)*>
<!ATTLIST manpage name CDATA #REQUIRED section CDATA #REQUIRED desc CDATA #IMPLIED>
<!ELEMENT arg (#PCDATA)>
<!ELEMENT p (#PCDATA | arg | url | manref | opt | file )*>
<!ELEMENT synopsis (cmd | p)+>
<!ELEMENT description (p)+>
<!ELEMENT section (p | option)*>
<!ATTLIST section name CDATA #REQUIRED>
<!ELEMENT option (#PCDATA | p | optdesc)*>
<!ELEMENT optdesc (#PCDATA | p )*>
<!ELEMENT cmd (#PCDATA | arg | opt)*>
<!ELEMENT options (p | option)*>
<!ELEMENT seealso (p)*>
<!ELEMENT opt (#PCDATA)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT manref EMPTY>
<!ATTLIST manref name CDATA #REQUIRED section CDATA #REQUIRED href CDATA #IMPLIED>
<!ELEMENT url EMPTY>
<!ATTLIST url href CDATA #REQUIRED>

=== jonathanhickford/rpi-shairport-sync/shairport-sync/man/shairport-sync.7.xml
<?xml version="1.0"?><!--*-nxml-*-->
<!DOCTYPE manpage SYSTEM "xmltoman.dtd">
<?xml-stylesheet type="text/xsl" href="xmltoman.xsl" ?>

<!--
  This man pager source file is part of shairport-sync.
  Copyright (c) Mike Brady 2014
  All rights reserved.
 
  Permission is hereby granted, free of charge, to any person
  obtaining a copy of this software and associated documentation
  files (the "Software"), to deal in the Software without
  restriction, including without limitation the rights to use,
  copy, modify, merge, publish, distribute, sublicense, and/or
  sell copies of the Software, and to permit persons to whom the
  Software is furnished to do so, subject to the following conditions:
 
  The above copyright notice and this permission notice shall be
  included in all copies or substantial portions of the Software.
 
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
  OTHER DEALINGS IN THE SOFTWARE.
-->

  <manpage name="shairport-sync" section="7" desc="Synchronised Audio Player for iTunes / AirPlay">

	<synopsis>
	<!--
      <cmd>shairport-sync <opt>-D</opt> <arg>interface</arg></cmd>
  -->
      <cmd>shairport-sync  <opt>[-dvw]</opt>
      <opt>[-A </opt><arg>name</arg><opt>]</opt>
      <opt>[-a </opt><arg>latency</arg><opt>]</opt>
      <opt>[-B </opt><arg>command</arg><opt>]</opt>
      <opt>[-E </opt><arg>command</arg><opt>]</opt>
      <opt>[-i </opt><arg>latency</arg><opt>]</opt>
      <opt>[-m </opt><arg>backend</arg><opt>]</opt>
      <opt>[-o </opt><arg>backend</arg><opt>]</opt>
      <opt>[-r </opt><arg>threshold</arg><opt>]</opt>
      <opt>[-S </opt><arg>mode</arg><opt>]</opt>
      <opt>[-t </opt><arg>timeout</arg><opt>]</opt>
      <opt>[-- </opt><arg>audio_backend_options</arg><opt>]</opt>
      </cmd>
      <cmd>shairport-sync <opt>-D</opt></cmd>
      <cmd>shairport-sync <opt>-h</opt></cmd>
      <cmd>shairport-sync <opt>-k</opt></cmd>
      <cmd>shairport-sync <opt>-h</opt></cmd>
      <cmd>shairport-sync <opt>-R</opt></cmd>
      <cmd>shairport-sync <opt>-V</opt></cmd>
	</synopsis>

  <description>
    <p>shairport-sync  plays  audio  streamed  from  iTunes or from an AirPlay
    device to an audio device connected via an audio back end. (At present,
    only an ALSA audio back end has been implemented.)</p>

    <p> A feature of shairport-sync is that the audio is played synchronously.
    This means that if many devices are playing the same stream at the same
    time, all the outputs will stay in step with one another.
    This allows multiple devices play the same source without getting out of phase with one another,
    enabling, for example, simultaneous multi-room operation.
    </p>

	</description>

	<options>

    <p>Many  of  the options take sensible default values, so you can normally
    ignore most of them. See the EXAMPLES section for typical usages.</p>

    <p>The command line for shairport-sync can take two kinds of options:
    regular  program  options  and audio backend options.  Program options are
    always listed first, followed by any audio backend options separated by
    a <b>--</b> symbol.</p>
    
  <section name="Program Options">
  <p>These options are used by shairport-sync itself.</p>
  </section>
  
	  <option>
		<p><opt>-A | --AirPlayLatency=</opt><arg>latency</arg></p>
		<optdesc><p>
		Use this latency, in frames, for audio streamed from an AirPlay
    device. The default is 88,200 frames, where there are 44,100
    frames to the second.
    </p></optdesc>
	  </option>

	  <option>
		<p><opt>-a </opt><arg>service name</arg><opt> | --name=</opt><arg>service name</arg></p>
		<optdesc><p>
		Use this service name to identify this player in iTunes, etc.
    The default name is "Shairport Sync on &lt;hostname&gt;".
    </p></optdesc>
	  </option>

	  <option>
		<p><opt>-B </opt><arg>program</arg><opt> | --on-start=</opt><arg>program</arg></p>
		<optdesc><p>
		Execute <arg>program</arg> when playback is about to begin. Specify the 
		full path to the program, e.g. <file>/usr/bin/logger</file>.
		Executable scripts can be used, but they must have <file>#!/bin/sh</file> (or
		whatever is appropriate) in the headline.</p>
		
		<p>If you want shairport-sync to wait until the command has
		completed before starting to play, select the <opt>-w</opt> option as well.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-D | --disconnectFromOutput</opt></p>
		<optdesc><p>
		Disconnect the shairport-sync daemon from the output device and
    exit. (Requires that the daemon has written its PID to an agreed
    file -- see the <opt>-d</opt> option).
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-d | --daemon</opt></p>
		<optdesc><p>
		Instruct shairport-sync to demonise itself. It will write its
    Process ID (PID) to a file, usually at
    /var/run/shairport-sync.pid, which is used by the
    <opt>-k</opt>, <opt>-D</opt> and <opt>-R</opt> options to locate
    the daemon at a later time.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-E </opt><arg>program</arg><opt> | --on-stop=</opt><arg>program</arg></p>
		<optdesc><p>
		Execute <arg>program</arg> when playback has ended. Specify the 
		full path to the program, e.g. <file>/usr/bin/logger</file>.
		Executable scripts can be used, but they must have <file>#!/bin/sh</file> (or
		whatever is appropriate) in the headline.</p>		
		<p>If you want shairport-sync to wait until the command has
		completed before continuing, select the <opt>-w</opt> option as well.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-h | --help</opt></p>
		<optdesc><p>
		Print brief help message and exit.
		</p></optdesc>
	  </option>

    <option>
		<p><opt>-i | --iTunesLatency=</opt><arg>latency</arg></p>
		<optdesc><p>
		Use this latency, in frames, for audio streamed from an iTunes
    source. The default is 99,400 frames, where there are 44,100
    frames to the second.
    </p></optdesc>
	  </option>

	  <option>
		<p><opt>-k | --kill</opt></p>
		<optdesc><p>
		Kill the shairport-sync daemon and exit. (Requires that the daemon has
		written its PID to an agreed file -- see the <opt>-d</opt> option).
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-m </opt><arg>mdnsbackend</arg><opt> | --mdns=</opt><arg>mdnsbackend</arg></p>
		<optdesc><p>
		Force the use of the specified mDNS backend to advertise the
    player on the network. The default is to try them all until one
    works.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-o </opt><arg>outputbackend</arg><opt> | --output=</opt><arg>outputbackend</arg></p>
		<optdesc><p>
		Force the use of the specified output backend to play the audio.
    The default is to try the first one. (This is not used at
    present.)
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-p </opt><arg>port</arg><opt> | --port=</opt><arg>port</arg></p>
		<optdesc><p>
		Listen for play requests on <arg>port</arg>. The default is to use port
    5000.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-R | --reconnectoToOutput</opt></p>
		<optdesc><p>
		Reconnect the shairport-sync daemon to the output device and
    exit. It may take a few seconds to synchronise. (Requires  that
    the daemon has written its PID to an agreed file -- see the <opt>-d</opt>
    option).
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-r </opt><arg>threshold</arg><opt> | --resync=</opt><arg>threshold</arg></p>
		<optdesc><p>
		Resynchronise if timings differ by more than <arg>threshold</arg> frames.
    If the output timing differs from the source timing by more than
    the threshold, output will be muted and a full resynchronisation
    will occur. The default threshold is 2,205 frames, i.e. 50
    milliseconds. Specify <opt>0</opt> to disable resynchronisation.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-S </opt><arg>mode</arg><opt> | --stuffing=</opt><arg>mode</arg></p>
		<optdesc><p>
		Stuff the audio stream using the <arg>mode</arg>.  "Stuffing" refers to the
    process of adding or removing frames of audio  to  or  from  the
    stream sent to the output device to keep it exactly in synchrony
    with the player.
    The default mode, <opt>basic</opt>, is normally almost  completely  inaudible.
    The  alternative mode, <opt>soxr</opt>, is even less obtrusive but
    requires much more processing power. For this mode, support for
    libsoxr, the SoX Resampler Library, must be selected when
    shairport-sync is compiled.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-t </opt><arg>timeout</arg><opt> | --timeout=</opt><arg>timeout</arg></p>
		<optdesc><p>
		Exit play mode if the stream disappears for  more  than  <arg>timeout</arg>
    seconds.</p>
    <p>When shairport-sync plays an audio stream, it startes a play
    session and will return a busy signal to any other sources that
    attempt to use it. If the audio stream disappears for longer
    than <arg>timeout</arg> seconds, the play session will be terminated.
    If you  specify a timeout time of <opt>0</opt>,
    shairport-sync will never signal that
    it is busy and will not prevent other sources from "barging in"
    on an existing play session. The default value is 120 seconds.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-V | --version</opt></p>
		<optdesc><p>
		Print version information and exit.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-v | --verbose</opt></p>
		<optdesc><p>
		Print debug information. Repeat up to three times to get more detail.
		</p></optdesc>
	  </option>

	  <option>
		<p><opt>-w | --wait-cmd</opt></p>
		<optdesc><p>
